channels:
- conda-forge
- bioconda
- defaults
dependencies:
- pip
- numpy
- networkx>=2
- biom-format
- pandas>=1
- scikit-bio
- statsmodels
- h5py
- python=3
- fastspar>=0.0.7
- armadillo=8
- pip:
  - scipy<=1.10.1,>=1.8.0
  - SCNIC