[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "SCNIC"
dynamic = ["version"]
description = "A tool for finding and summarizing modules of highly correlated observations in compositional data"
readme = "README.md"
license = "BSD-3-Clause"
authors = [
    { name = "Lozupone Lab", email = "lozuponelab.dev@olucdenver.onmicrosoft.com" }
]
urls = { Homepage = "https://github.com/lozuponelab/SCNIC/", Download = "https://github.com/lozuponelab/SCNIC/tarball/0.6.6" }
requires-python = ">=3.10, <3.13"
dependencies = [
    "numpy",
    "networkx>=2",
    "biom-format",
    "pandas>=1",
    "scikit-bio",
    "statsmodels",
    "tqdm",
    "h5py",
    "scipy>=1.11.0",
    "python-louvain"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering"
]

[project.optional-dependencies]
test = ["pytest"]

[project.scripts]
scnic = "SCNIC.cli.SCNIC_analysis:main"
scnic-analysis = "SCNIC.cli.SCNIC_analysis:main"
scnic-module-enrichment = "SCNIC.cli.module_enrichment:main"

[tool.setuptools.packages.find]
include = ["SCNIC*"]

[tool.setuptools_scm]
write_to = "SCNIC/_version.py"
fallback_version = "0.0.0"
local_scheme = "no-local-version" ## excludes local distance hash for uncomitted changes 
version_scheme = "no-guess-dev" ## default: "guess-next-dev", other options: "post-release", "no-guess-dev"