name: unit tests for scnic
run-name: attempt-one-testing-after-major-changes

on:
  workflow_dispatch:
  push:
    branches:
      - dev_MA_2026
      #- main
  pull_request:

permissions:
  contents: read
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"] ## madi edit: add testing for newer python versions (will need to add 3.13 soon)
    # Set it to default use bash in interactive mode (required for miniconda setup)
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version:  ${{ matrix.python-version }}
          channels: conda-forge,bioconda,nodefaults
          auto-activate-base: false
          environment-file: gh_actions_env.yml ## temp use dev conda env instead of environment.yml 
        
      - name: give python version
        run: python -c "import sys; print(sys.version)"
      
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .
      
      - name: run smoke tests
        run: bash tests/smoke_test.sh

      - name: test with pytest
        run: |
          python -m pytest tests/*.py